#!/usr/bin/env bash
# Provision THIS Mac for Developer ID signing + notarization using secrets
# stored in Google Secret Manager. Safe to re-run (idempotent).
#
# What it does:
#   1. Pulls the Developer ID cert + notary API key from Secret Manager.
#   2. Creates a dedicated 'oxos-signing' keychain and imports the cert so
#      codesign can use it non-interactively (no GUI password prompt).
#   3. Writes the notary API key to ~/.config/oxos-signing/ and an env.sh that
#      both the Slates (Tauri) and Anvil (make-app.sh) builds source.
#
# Usage:  ./provision.sh        (run once per machine; re-run to rotate)
set -euo pipefail
cd "$(dirname "$0")"
source ./config.sh

check_gcloud_auth
require security
require codesign
xcrun notarytool --version >/dev/null 2>&1 || die "notarytool unavailable (install Xcode Command Line Tools)"

echo "▸ pulling secrets from project '$PROJECT'…"
mkdir -p "$SIGNING_HOME"; chmod 700 "$SIGNING_HOME"
tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT

secret_get "$SECRET_P12"           | base64 -D -o "$tmp/cert.p12"
secret_get "$SECRET_NOTARY_P8"     | base64 -D -o "$P8_PATH"; chmod 600 "$P8_PATH"
P12_PASS="$(secret_get "$SECRET_P12_PASS")"
IDENTITY="$(secret_get "$SECRET_IDENTITY")"
KEY_ID="$(secret_get "$SECRET_NOTARY_KEY_ID")"
ISSUER="$(secret_get "$SECRET_NOTARY_ISSUER")"
# Apple Team ID + iOS cert are optional — present once the iOS client is set up.
TEAM_ID=""; secret_exists "$SECRET_TEAM_ID" && TEAM_ID="$(secret_get "$SECRET_TEAM_ID")"

# --- dedicated keychain -----------------------------------------------------
# Per-machine random keychain password; never leaves this Mac.
KC_PASS="$(security find-generic-password -s oxos-signing-kc -w 2>/dev/null || true)"
if [ -z "$KC_PASS" ]; then
  KC_PASS="$(openssl rand -hex 32)"   # pipe-free (tr|head SIGPIPEs under set -o pipefail)
  security add-generic-password -s oxos-signing-kc -a "$USER" -w "$KC_PASS" 2>/dev/null || true
fi

if [ ! -f "$KEYCHAIN_PATH" ]; then
  echo "▸ creating keychain $KEYCHAIN_NAME"
  security create-keychain -p "$KC_PASS" "$KEYCHAIN_PATH"
fi
security set-keychain-settings "$KEYCHAIN_PATH"            # no auto-lock timeout
security unlock-keychain -p "$KC_PASS" "$KEYCHAIN_PATH"

# Add to the user search list without duplicating it.
others="$(security list-keychains -d user | sed -e 's/^[[:space:]]*"//' -e 's/"$//' | grep -v "$KEYCHAIN_NAME" || true)"
# shellcheck disable=SC2086
security list-keychains -d user -s "$KEYCHAIN_PATH" $others

# Import the cert (idempotent: ignore "already exists").
security import "$tmp/cert.p12" -k "$KEYCHAIN_PATH" -P "$P12_PASS" \
  -T /usr/bin/codesign -T /usr/bin/security 2>/dev/null || true
# Allow codesign to use the key without an interactive prompt.
security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KC_PASS" "$KEYCHAIN_PATH" >/dev/null

# Apple intermediate CAs. A .p12 built with `openssl pkcs12` holds ONLY the leaf cert, so the chain
# can't validate (find-identity -v shows 0 valid) until the issuing intermediate is in the keychain.
# Keychain Access exports bundle these automatically; openssl ones don't. Import the ones our certs
# chain to (Developer ID → G2, Apple Distribution/WWDR → G3). Roots are already system-trusted.
import_apple_ca() {
  local url="$1"
  local out="$tmp/$(basename "$url")"
  if curl -fsSL "$url" -o "$out" 2>/dev/null; then
    security import "$out" -k "$KEYCHAIN_PATH" 2>/dev/null || true
  else
    echo "  ! could not fetch $(basename "$url") — chain may not validate offline"
  fi
}
import_apple_ca https://www.apple.com/certificateauthority/DeveloperIDG2CA.cer
import_apple_ca https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer

# --- verify the identity is usable -----------------------------------------
if ! security find-identity -v -p codesigning "$KEYCHAIN_PATH" | grep -q "$IDENTITY"; then
  die "identity not found in keychain after import: $IDENTITY"
fi
echo "✓ signing identity ready: $IDENTITY"

# --- iOS distribution cert (optional) --------------------------------------
# Imported into the same keychain so a local `apple/make-ios.sh` can sign + upload to TestFlight.
if secret_exists "$SECRET_IOS_P12"; then
  secret_get "$SECRET_IOS_P12" | base64 -D -o "$tmp/ios.p12"
  IOS_P12_PASS="$(secret_get "$SECRET_IOS_P12_PASS")"
  security import "$tmp/ios.p12" -k "$KEYCHAIN_PATH" -P "$IOS_P12_PASS" \
    -T /usr/bin/codesign -T /usr/bin/xcodebuild 2>/dev/null || true
  security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KC_PASS" "$KEYCHAIN_PATH" >/dev/null
  if security find-identity -v -p codesigning "$KEYCHAIN_PATH" | grep -q "Apple Distribution"; then
    echo "✓ iOS Apple Distribution cert imported"
  else
    echo "  ! iOS cert imported but 'Apple Distribution' identity not visible — check the .p12"
  fi
fi

# --- env file the builds source --------------------------------------------
cat > "$ENV_FILE" <<EOF
# Generated by provision.sh — source before building Slates or Anvil.
export APPLE_SIGNING_IDENTITY="$IDENTITY"
export APPLE_API_KEY="$KEY_ID"          # App Store Connect Key ID
export APPLE_API_ISSUER="$ISSUER"       # App Store Connect Issuer ID
export APPLE_API_KEY_PATH="$P8_PATH"    # path to the AuthKey .p8
export APPLE_TEAM_ID="$TEAM_ID"         # 10-char Team ID (consumed by apple/make-ios.sh)
export SIGN_ID="\$APPLE_SIGNING_IDENTITY"  # alias consumed by Anvil's make-app.sh
EOF
chmod 600 "$ENV_FILE"

echo "✓ wrote $ENV_FILE"

# --- daemon APNs config (optional) -----------------------------------------
# If the APNs key is in Secret Manager, assemble ~/.config/anvil/apns-key.json so the daemon's
# push sender (anvild/src/push/apns.ts) is ready. Only meaningful on the daemon host.
if secret_exists "$SECRET_APNS_P8" && [ -n "$TEAM_ID" ]; then
  require jq
  mkdir -p "$ANVIL_CONFIG_DIR"; chmod 700 "$ANVIL_CONFIG_DIR"
  secret_get "$SECRET_APNS_P8" | base64 -D -o "$tmp/apns.p8"
  APNS_KEY_ID="$(secret_get "$SECRET_APNS_KEY_ID")"
  jq -n --arg key "$(cat "$tmp/apns.p8")" --arg kid "$APNS_KEY_ID" --arg team "$TEAM_ID" --arg bundle "$APNS_BUNDLE_ID" \
    '{keyId:$kid, teamId:$team, bundleId:$bundle, key:$key, production:true}' > "$APNS_KEY_JSON"
  chmod 600 "$APNS_KEY_JSON"
  echo "✓ wrote $APNS_KEY_JSON (restart the daemon to pick it up)"
fi
echo
echo "Next: in any build shell run"
echo "    source \"$ENV_FILE\""
echo "  then build as usual — Slates: 'npm run tauri:build', Anvil: './make-app.sh'."
echo "Verify a build with:  spctl -a -vvv --type exec /path/to/App.app"
