// swift-tools-version:5.9
import PackageDescription

// SwiftPM target for the macOS shell — used both for `swift run` (dev) and as the build
// product that make-app.sh packages into a distributable, ad-hoc-signed Anvil.app with no
// Xcode required. project.yml remains for opening the app in Xcode.app. See apple/README.md.
let package = Package(
    name: "Anvil",
    platforms: [.macOS(.v13)],
    dependencies: [
        // Auto-update for release builds installed outside the Mac App Store. make-app.sh embeds
        // Sparkle.framework into Anvil.app and signs its nested helpers; SparkleUpdater.swift wires
        // it to the "Check for Updates…" menu command (macOS only — guarded by #if os(macOS)).
        .package(url: "https://github.com/sparkle-project/Sparkle", from: "2.6.0"),
    ],
    targets: [
        .executableTarget(
            name: "Anvil",
            dependencies: [.product(name: "Sparkle", package: "Sparkle")],
            path: "Sources/Anvil",
            resources: [.copy("web")] // bundled web client (generated by anvild/web/bundle-native.ts)
        ),
    ]
)
