// swift-tools-version:5.9
import PackageDescription

// SwiftPM target for the macOS shell — used both for `swift run` (dev) and as the build
// product that make-app.sh packages into a distributable, ad-hoc-signed Anvil.app with no
// Xcode required. project.yml remains for opening the app in Xcode.app. See apple/README.md.
let package = Package(
    name: "Anvil",
    platforms: [.macOS(.v13)],
    targets: [
        .executableTarget(
            name: "Anvil",
            path: "Sources/Anvil",
            resources: [.copy("web")] // bundled web client (generated by anvild/web/bundle-native.ts)
        ),
    ]
)
